# -*- coding: utf-8 -*-
"""smart_meter3.0

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sBc1mvHj13R-iAg_68grR6gSkseBfzMI

Kanav garg
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Replace with your actual path in Drive
file_path = '/content/drive/MyDrive/advanced_house_usage.csv'
df = pd.read_csv(file_path)

df.head()

from sklearn.ensemble import IsolationForest

# Create a new feature: usage ratio = avg_usage / peak_load
df['usage_ratio'] = df['avg_usage'] / df['peak_load']

# Train Isolation Forest on usage ratio
model = IsolationForest(contamination=0.1, random_state=42)
df['anomaly'] = model.fit_predict(df[['usage_ratio']])

# Convert output to readable labels
df['anomaly_label'] = df['anomaly'].map({1: 'Normal', -1: 'Anomaly'})

# Check results
df[['house_id', 'peak_load', 'avg_usage', 'usage_ratio', 'anomaly_label']].head()

#!pip install -q streamlit pyngrok

from pyngrok import ngrok

# Only run this ONCE (replace with your token)
ngrok.set_auth_token("2whAAMu9D6dCaeouOFkTzuI8GkB_3v6goQQWUPavogQHpQZ2W")

import joblib

# Save the trained model and scaler (if any)
joblib.dump(model, 'isolation_model.pkl')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import joblib
# import numpy as np
# 
# # Load the model
# model = joblib.load("isolation_model.pkl")
# 
# st.title("🔍 Smart Energy Anomaly Detector")
# st.markdown("Enter the meter data below:")
# 
# # Input form
# season = st.selectbox("Season", ["Summer", "Winter", "Rainy"])
# month = st.slider("Month (1-12)", 1, 12, 6)
# peak_load = st.number_input("Peak Load (in kWh)", min_value=100.0, max_value=2000.0, step=10.0)
# avg_usage = st.number_input("Average Monthly Usage (in kWh)", min_value=10.0, max_value=2000.0, step=10.0)
# 
# # Predict
# if st.button("Check Usage"):
#     usage_ratio = avg_usage / peak_load
#     prediction = model.predict([[usage_ratio]])[0]
#     result = "🔴 Anomaly" if prediction == -1 else "🟢 Normal"
#     st.subheader(f"Result: {result}")
#

from pyngrok import conf, ngrok
import os
import time
import threading

# (Optional) Authenticate ngrok - paste your token if needed
conf.get_default().auth_token = "2whAAMu9D6dCaeouOFkTzuI8GkB_3v6goQQWUPavogQHpQZ2W"  # Only required first time

# Function to run Streamlit
def run_streamlit():
    os.system('streamlit run app.py')

# Start Streamlit in background
thread = threading.Thread(target=run_streamlit)
thread.start()

# Allow time to start
time.sleep(5)

# Create public URL
# Change is on this line: provide the port within the addr argument
public_url = ngrok.connect(addr="8501")
print("🔗 Your Streamlit app is live at:", public_url)

# prompt: download pkl file

from google.colab import files

files.download('isolation_model.pkl')

